// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiTiC0ieT0XT5JC-fGH9J41FWooOEz9e8',
    appId: '1:518532186076:web:db88387980559b16e19919',
    messagingSenderId: '518532186076',
    projectId: 'authtutorial-ec2d2',
    authDomain: 'authtutorial-ec2d2.firebaseapp.com',
    storageBucket: 'authtutorial-ec2d2.appspot.com',
    measurementId: 'G-CHTS0JB1GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClIvdanS5G1Q4bVfYLC-lGAjBBgIkPsFw',
    appId: '1:518532186076:android:67498e69778c8398e19919',
    messagingSenderId: '518532186076',
    projectId: 'authtutorial-ec2d2',
    storageBucket: 'authtutorial-ec2d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjSHbGqOkiKIueajeEAaCEGqC59N4HjcY',
    appId: '1:518532186076:ios:bee2fa93b19e0e1ce19919',
    messagingSenderId: '518532186076',
    projectId: 'authtutorial-ec2d2',
    storageBucket: 'authtutorial-ec2d2.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjSHbGqOkiKIueajeEAaCEGqC59N4HjcY',
    appId: '1:518532186076:ios:bee2fa93b19e0e1ce19919',
    messagingSenderId: '518532186076',
    projectId: 'authtutorial-ec2d2',
    storageBucket: 'authtutorial-ec2d2.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiTiC0ieT0XT5JC-fGH9J41FWooOEz9e8',
    appId: '1:518532186076:web:7b15facd4283fbcce19919',
    messagingSenderId: '518532186076',
    projectId: 'authtutorial-ec2d2',
    authDomain: 'authtutorial-ec2d2.firebaseapp.com',
    storageBucket: 'authtutorial-ec2d2.appspot.com',
    measurementId: 'G-1B7MMVKFFN',
  );
}
